Repository LetsCareer-A/LetsCareerA-BE, pull requests merged in 2024-09, with the labels that each got.

#22 #21 [feat] 투두 토글 변경
  src/main/java/com/example/letscareer/common/exception/enums/ErrorCode.java
  src/main/java/com/example/letscareer/common/exception/enums/SuccessCode.java
  src/main/java/com/example/letscareer/todo/controller/TodoController.java
  src/main/java/com/example/letscareer/todo/domain/Todo.java
  src/main/java/com/example/letscareer/todo/service/TodoService.java
Labels: feat

#25 #24 [fix] schedule 등록 시 오류 수정
  src/main/java/com/example/letscareer/career/service/CareerService.java
  src/main/java/com/example/letscareer/stage/domain/Stage.java
Labels: bug

#26 #23 4.8 중간 전형 회고
  src/main/java/com/example/letscareer/common/exception/enums/ErrorCode.java
  src/main/java/com/example/letscareer/common/exception/enums/SuccessCode.java
  src/main/java/com/example/letscareer/mid_review/controller/MidReviewController.java
  src/main/java/com/example/letscareer/mid_review/domain/MidReview.java
  src/main/java/com/example/letscareer/mid_review/dto/request/PostMidReviewRequest.java
  src/main/java/com/example/letscareer/mid_review/repository/MidReviewRepository.java
  src/main/java/com/example/letscareer/mid_review/service/MidReviewService.java
Labels: feat

#29 #27 [feat] 4.9 면접 전형 회고
  src/main/java/com/example/letscareer/common/exception/enums/SuccessCode.java
  src/main/java/com/example/letscareer/int_review/controller/IntReviewController.java
  src/main/java/com/example/letscareer/int_review/dto/request/PostIntReviewRequest.java
  src/main/java/com/example/letscareer/int_review/repository/IntReviewRepository.java
  src/main/java/com/example/letscareer/int_review/service/IntReviewService.java
  src/main/java/com/example/letscareer/schedule/domain/Progress.java
Labels: feat

#30 #28 [feat] 빠른회고 리스트 가져오기
  src/main/java/com/example/letscareer/int_review/domain/IntReview.java
  src/main/java/com/example/letscareer/int_review/repository/IntReviewRepository.java
  src/main/java/com/example/letscareer/int_review/service/IntReviewService.java
  src/main/java/com/example/letscareer/mid_review/controller/MidReviewController.java
  src/main/java/com/example/letscareer/mid_review/domain/MidReview.java
  src/main/java/com/example/letscareer/mid_review/dto/FastDTO.java
  src/main/java/com/example/letscareer/mid_review/dto/response/FastReviewsResponse.java
  src/main/java/com/example/letscareer/mid_review/repository/MidReviewRepository.java
  src/main/java/com/example/letscareer/mid_review/service/MidReviewService.java
  src/main/java/com/example/letscareer/schedule/controller/ScheduleController.java
  src/main/java/com/example/letscareer/schedule/dto/StageDTO.java
  src/main/java/com/example/letscareer/schedule/dto/request/SchedulePostRequest.java
  src/main/java/com/example/letscareer/schedule/service/ScheduleService.java
  src/main/java/com/example/letscareer/stage/domain/Stage.java
  src/main/java/com/example/letscareer/stage/repository/StageRepository.java
Labels: feat

#85 #84 [refactor] 회고 보드 api 수정
  src/main/java/com/example/letscareer/schedule/domain/dto/CompanyReviewDTO.java
  src/main/java/com/example/letscareer/schedule/service/ScheduleService.java
Labels: refactor

#87 #86 [refactor] 회고보드 paging 수정
  src/main/java/com/example/letscareer/schedule/service/ScheduleService.java
Labels: refactor

#89 #88 [refactor] 커리어 조회 필터링 추가
  src/main/java/com/example/letscareer/career/controller/CareerController.java
  src/main/java/com/example/letscareer/career/domain/repository/CareerRepository.java
  src/main/java/com/example/letscareer/career/service/CareerService.java
Labels: refactor

#92 #91 [refactor] 커리어 전체 조회 시 어필할 커리어 등록된 커리어 표시되게 수정
  src/main/java/com/example/letscareer/appealCareer/domain/repository/AppealCareerRepository.java
  src/main/java/com/example/letscareer/career/controller/CareerController.java
  src/main/java/com/example/letscareer/career/domain/dto/CareerWithAppealDTO.java
  src/main/java/com/example/letscareer/career/domain/dto/converter/CareerConverter.java
  src/main/java/com/example/letscareer/career/domain/dto/response/GetAllCareersResponse.java
  src/main/java/com/example/letscareer/career/service/CareerService.java
Labels: refactor

#94 #93 [refactor] 캐싱 커리어 보드에 적용
  src/main/java/com/example/letscareer/career/service/CareerService.java
Labels: refactor

#96 [fix] 캐싱 커리어 보드 조회 오류 수정
  src/main/java/com/example/letscareer/career/service/CareerService.java
Labels: fix

#98 [refactor] 전형 단계 상태 추가
  src/main/java/com/example/letscareer/stage/domain/model/Status.java
  src/main/java/com/example/letscareer/stage/service/StageService.java
Labels: refactor
